name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Installs
      run: sudo apt-get install doxygen graphviz wget libnetcdf-dev libgsl-dev
#    - name: libs
#      run: cd libs ; ./build.sh
    - name: make
      run: cd src ; make
#    - name: make check
#      run: make check
