name: codecov

on: [push, pull_request]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: fetch
      uses: actions/checkout@master
    - name: install
      run: sudo apt-get update ; sudo apt-get install gnuplot lcov libgsl-dev libnetcdf-dev libhdf5-dev zlib1g-dev
    - name: make
      run: cd ./src ; STATIC=0 COV=1 make
    - name: check
      run: cd ./src ; STATIC=0 COV=1 make check
    - name: coverage
      run: cd ./src ; STATIC=0 COV=1 make coverage
    - name: upload
      uses: codecov/codecov-action@v2
      with:
        directory: ./src/
