on:
  push:
    branches: 
      - master

jobs:

  deploying_mkdoc:
    runs-on: ubuntu-latest
    steps:
      - name: mkdocs
        uses: actions/checkout@v3
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: installing mkdocs
        run: pip install mkdocs ; pip install mkdocs-material
        run: cd docs ; mkdocs gh-deploy --force --clean --verbose
        
  deploying_doxygen:
    runs-on: ubuntu-latest
    steps:
    - name: doxygen
       uses: mattnotmitt/doxygen-action@v1.9.1
       with:
         doxyfile-path: "./Doxyfile"
         working-directory: "./docs"

    - name: deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/html
        destination_dir: doxygen

