name: test case

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install
      run: sudo apt-get install wget gnuplot
    - name: libs
      run: cd libs ; ./build.sh nc4
    - name: make
      run: cd src ; make
    - name: example
      run: cd example ; ./run.sh
